#!/usr/bin/env bash
#
# One-time workstation fix: rename local Pro hostname easelog.pro -> easelogs.pro
# in /etc/hosts and nginx. Does NOT touch Community (easelogs.local) or deploy paths.
#
# Run: sudo bash ~/EaseLogs/scripts/migrate-pro-hostname-to-easelogs-pro.sh
#
set -euo pipefail

readonly NEW_HOST="easelogs.pro"
readonly OLD_HOST="easelog.pro"
readonly CERT_DIR="/etc/nginx/certs/easelog-pro"
readonly NGINX_CONF="/etc/nginx/conf.d/easelogs.pro.conf"
readonly OLD_NGINX_CONF="/etc/nginx/conf.d/easelog.pro.conf"
readonly HOSTS_FILE="/etc/hosts"
readonly REPO_ROOT="${EASELOGS_REPO:-$HOME/EaseLogs}"

if [[ $EUID -ne 0 ]]; then
  echo "Run with sudo: sudo bash $0" >&2
  exit 1
fi

step() { echo ""; echo "==> $1"; }

resolve_cert_paths() {
  if [[ -f "$CERT_DIR/${NEW_HOST}+1.pem" && -f "$CERT_DIR/${NEW_HOST}+1-key.pem" ]]; then
    SSL_CERT="$CERT_DIR/${NEW_HOST}+1.pem"
    SSL_KEY="$CERT_DIR/${NEW_HOST}+1-key.pem"
    return 0
  fi
  if [[ -f "$CERT_DIR/${NEW_HOST}.pem" && -f "$CERT_DIR/${NEW_HOST}-key.pem" ]]; then
    SSL_CERT="$CERT_DIR/${NEW_HOST}.pem"
    SSL_KEY="$CERT_DIR/${NEW_HOST}-key.pem"
    return 0
  fi
  if [[ -f "$CERT_DIR/${OLD_HOST}.pem" && -f "$CERT_DIR/${OLD_HOST}-key.pem" ]]; then
    echo "    Using existing mkcert files for $OLD_HOST (regenerate for $NEW_HOST when convenient)"
    SSL_CERT="$CERT_DIR/${OLD_HOST}.pem"
    SSL_KEY="$CERT_DIR/${OLD_HOST}-key.pem"
    return 0
  fi
  return 1
}

step "Update $HOSTS_FILE"
if grep -qE "[[:space:]]${NEW_HOST}([[:space:]]|$)" "$HOSTS_FILE" 2>/dev/null; then
  echo "    $NEW_HOST already in hosts"
else
  echo "127.0.0.1 ${NEW_HOST}" >> "$HOSTS_FILE"
  echo "    Added 127.0.0.1 ${NEW_HOST}"
fi

if grep -qE "[[:space:]]${OLD_HOST}([[:space:]]|$)" "$HOSTS_FILE" 2>/dev/null; then
  echo "    Note: $OLD_HOST still in hosts (harmless; remove manually if you want only $NEW_HOST)"
fi

step "Resolve TLS certificate paths"
if ! resolve_cert_paths; then
  echo "    No certificate found under $CERT_DIR"
  echo "    Generate before reloading nginx:"
  echo "      mkcert ${NEW_HOST}"
  echo "      sudo mkdir -p $CERT_DIR"
  echo "      sudo mv ${NEW_HOST}+1.pem ${NEW_HOST}+1-key.pem $CERT_DIR/"
  exit 1
fi
echo "    ssl_certificate:     $SSL_CERT"
echo "    ssl_certificate_key: $SSL_KEY"

step "Write nginx config $NGINX_CONF"
cat > "$NGINX_CONF" <<EOF
# EaseLogs Pro — local intranet (generated by migrate-pro-hostname-to-easelogs-pro.sh)

server {
    listen 80;
    server_name ${NEW_HOST};

    return 301 https://\$host\$request_uri;
}

server {
    listen 443 ssl;
    server_name ${NEW_HOST};
    client_max_body_size 25M;

    ssl_certificate ${SSL_CERT};
    ssl_certificate_key ${SSL_KEY};

    root /var/www/projects/easelog-pro/public;
    index index.php index.html;

    access_log /var/log/nginx/easelog-pro.access.log;
    error_log /var/log/nginx/easelog-pro.error.log;

    location / {
        try_files \$uri \$uri/ /index.php?\$query_string;
    }

    location ~ \\.php\$ {
        include fastcgi_params;
        fastcgi_pass unix:/run/php-fpm/php-fpm.sock;
        fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
        fastcgi_index index.php;
    }

    location ~ /\\.(?!well-known).* {
        deny all;
    }
}
EOF

if [[ -f "$OLD_NGINX_CONF" ]]; then
  step "Disable old nginx config"
  mv "$OLD_NGINX_CONF" "${OLD_NGINX_CONF}.disabled.$(date +%Y%m%d)"
  echo "    Renamed $OLD_NGINX_CONF -> ${OLD_NGINX_CONF}.disabled.*"
fi

step "Test and reload nginx"
nginx -t
systemctl reload nginx

step "Update Pro APP_URL if deploy exists"
if [[ -f /var/www/projects/easelog-pro/.env ]]; then
  sed -i "s|^APP_URL=.*|APP_URL=https://${NEW_HOST}|" /var/www/projects/easelog-pro/.env
  echo "    Set APP_URL=https://${NEW_HOST} in /var/www/projects/easelog-pro/.env"
  if id -u http &>/dev/null; then
    sudo -u "$(stat -c '%U' /var/www/projects/easelog-pro/.env)" \
      php /var/www/projects/easelog-pro/artisan config:clear 2>/dev/null || \
      php /var/www/projects/easelog-pro/artisan config:clear
  else
    php /var/www/projects/easelog-pro/artisan config:clear 2>/dev/null || true
  fi
fi

echo ""
echo "Migration complete. Verify:"
echo "  curl -k -I https://${NEW_HOST}"
echo "  curl -k -I https://easelogs.local"
echo "  $REPO_ROOT/scripts/verify-local-deployments.sh"
