@extends('layouts.app')

@section('title', 'Edit: ' . ($artwork->title ?: 'Untitled') . ' — ' . config('app.name'))

@section('content')
    <h2 class="page-heading">Edit artwork</h2>
    <p class="page-intro">Update the artwork details below. Blank inventory code or SKU values will be preserved or auto-generated by the system.</p>

    <form method="POST" action="{{ route('artworks.update', $artwork) }}">
        @csrf
        @method('PUT')
        @include('artworks._form')

        <div class="actions">
            <button type="submit" class="btn btn-primary">Save changes</button>
            <a href="{{ route('artworks.show', $artwork) }}" class="btn">Cancel</a>
        </div>
    </form>
@endsection
